env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - airbnb-base
  - plugin:prettier/recommended  # 添加 prettier 插件
overrides: []
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: {
  'import/no-unresolved': 'off',
  'import/extensions': 'off',
  'vue/multi-word-component-names': 'off',
  'no-param-reassign': 'off',
  "no-plusplus": 'off',
  "no-bitwise": 'off',
  'no-shadow': 'off'

}
